### ISSUE TITLE
[Tracking issue] Documentation coverage

### ISSUE THREAD

**Issue by MichaelDeciso** [opnsense/docs#104]
This is a tracking issue, meant to track which parts of the product have been documented, which parts haven't been, and which parts have documentation that is outdated or not up to standard.

This tree follows the menu structure of OPNsense:

- [x] Lobby https://docs.opnsense.org/manual/gui.html
  - [x] Dashboard: https://github.com/opnsense/docs/pull/112 ; also somewhat covered by https://docs.opnsense.org/manual/gui.html
  - [x] License (not needed) https://docs.opnsense.org/manual/gui.html
  - [x] Password https://docs.opnsense.org/manual/gui.html
  - [x] Logout https://docs.opnsense.org/manual/gui.html
- [x] Reporting
  - [x] Health https://docs.opnsense.org/manual/systemhealth.html
  - [x] Insight https://docs.opnsense.org/manual/how-tos/insight.html
  - [x] Netflow https://docs.opnsense.org/manual/netflow.html
  - [x] Settings https://docs.opnsense.org/manual/reporting_settings.html
  - [x] Traffic https://docs.opnsense.org/manual/reporting_traffic.html
- [ ] System
  - [x] Access
     - [x] Users https://docs.opnsense.org/manual/how-tos/user-local.html
     - [x] Groups https://docs.opnsense.org/manual/how-tos/user-local.html
     - [x] Servers
     - [x] Tester https://docs.opnsense.org/manual/how-tos/two_factor.html
   - [ ] Configuration
     - [x] Backups https://docs.opnsense.org/manual/how-tos/cloud_backup.html
     - [ ] Defaults
     - [ ] History
   - [ ] Firmware
     - [x] Updates https://github.com/opnsense/docs/pull/113
     - [ ] Plugins
     - [ ] Packages
     - [x] Changelog https://github.com/opnsense/docs/pull/129
     - [ ] Settings
     - [ ] Reporter
     - [x] Log file https://docs.opnsense.org/manual/logging.html
  - [ ] Gateways
     - [ ] Single https://docs.opnsense.org/manual/how-tos/multiwan.html
     - [ ] Group
     - [x] Log file https://docs.opnsense.org/manual/logging.html
  - [x] High Availability https://docs.opnsense.org/manual/hacarp.html
     - [ ] Settings
     - [ ] Status
  - [ ] Routes
     - [ ] Configuration
     - [ ] Status
     - [x] Log file https://docs.opnsense.org/manual/logging.html
  - [x] Settings #155
     - [x] Administration #155
     - [x] Cron #155
     - [x] General #155
     - [x] Logging https://github.com/opnsense/docs/pull/149
     - [x] Miscellaneous #155
     - [x] Tunables #155
  - [ ] Trust
     - [ ] Authorities
     - [x] Certificates https://docs.opnsense.org/manual/certificates.html
     - [ ] Revocation
  - [ ] Wizard
  - [ ] Log Files
     - [x] Backend https://docs.opnsense.org/manual/logging.html
     - [x] General https://docs.opnsense.org/manual/logging.html
     - [x] Web GUI https://docs.opnsense.org/manual/logging.html
  - [x] Diagnostics https://github.com/opnsense/docs/pull/126
     - [x] Activity
     - [x] Services
- [ ] Interfaces
  - [x] `[LAN]`/`[WAN]`/etc. https://github.com/opnsense/docs/pull/147
  - [x] Assignments https://github.com/opnsense/docs/pull/147
  - [x] Overview #151
  - [ ] Settings
  - [x] Wireless https://github.com/opnsense/docs/pull/141
    - [ ] Devices
    - [x] Log Files https://docs.opnsense.org/manual/logging.html
  - [x] Point-to-Point https://docs.opnsense.org/manual/how-tos/multiwan.html
    - [x] Devices https://docs.opnsense.org/manual/how-tos/multiwan.html
    - [x] Log Files https://docs.opnsense.org/manual/logging.html
  - [ ] Other Types #162 
    - [ ] Bridge
    - [ ] GIF
    - [ ] GRE
    - [ ] LAGG
    - [ ] VLAN
  - [x] Diagnostics https://github.com/opnsense/docs/pull/126
    - [x] ARP Table
    - [x] DNS Lookup
    - [x] NDP Table
    - [x] Packet Capture
    - [x] Ping
    - [x] Port Probe
    - [x] Trace Route
- [ ] Firewall
  - [x] Aliases https://docs.opnsense.org/manual/aliases.html
  - [ ] Rules
    - [ ] Floating
    - [ ] (interface-specific)
  - [x] NAT #139
    - [x] Port Forward
    - [x] One-to-One
    - [x] Outbound
    - [x] NPTv6 #134
  - [x] Shaper https://docs.opnsense.org/manual/how-tos/shaper.html https://docs.opnsense.org/manual/shaping.html
    - [x] Settings https://docs.opnsense.org/manual/how-tos/shaper.html
    - [x] Status https://docs.opnsense.org/manual/how-tos/shaper.html
  - [ ] Groups
  - [x] Virtual IPs (covered by CARP docs)
    - [x] Settings (covered by CARP docs)
    - [x] Status (covered by CARP docs)
  - [ ] Settings
    - [ ] Advanced
    - [ ] Normalization
    - [ ] Schedules
  - [ ] Log Files
    - [x] Live View https://docs.opnsense.org/manual/logging.html
    - [ ] Overview
    - [x] Plain View https://docs.opnsense.org/manual/logging.html
  - [x] Diagnostics https://github.com/opnsense/docs/pull/126
    - [x] pfInfo https://github.com/opnsense/docs/pull/126
    - [x] pfTop https://github.com/opnsense/docs/pull/126
    - [x] pfTables https://docs.opnsense.org/manual/aliases.html
    - [x] Sockets https://github.com/opnsense/docs/pull/126
    - [x] Status Dump https://github.com/opnsense/docs/pull/126
    - [x] Status Reset https://github.com/opnsense/docs/pull/126
    - [x] Status Summary https://github.com/opnsense/docs/pull/126
- [x] VPN https://docs.opnsense.org/manual/vpnet.html
  - [x] IPsec https://docs.opnsense.org/manual/vpnet.html#configuration
    - [x] Tunnel Settings
    - [ ] Mobile Clients
    - [x] Pre-Shared Keys
    - [ ] Advanced Settings
    - [ ] Status Overview
    - [ ] Lease Status
    - [ ] Security Association Database
    - [ ] Security Policy Database
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [x] OpenVPN https://docs.opnsense.org/manual/vpnet.html#configuration
    - [x] Servers
    - [x] Clients
    - [x] Client Specific Overrides
    - [x] Client Export
    - [x] Connection Status
    - [x] Log File https://docs.opnsense.org/manual/logging.html
- [ ] Services
  - [x] Captive Portal https://docs.opnsense.org/manual/captiveportal.html
    - [x] Administration
    - [x] Sessions
    - [x] Vouchers
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [x] DHCPv4 https://github.com/opnsense/docs/pull/127
    - [ ] (interface-specific)
    - [x] Relay #160
    - [ ] Leases
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [x] DHCPv6 https://github.com/opnsense/docs/pull/127
    - [x] Relay #160
    - [ ] Leases
  - [ ] Dnsmasq DNS
    - [ ] Settings
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [ ] Dynamic DNS
  - [ ] Intrusion Detection
    - [ ] Administration
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [x] Monit: https://github.com/opnsense/docs/commit/8231b1321868a03fbacd8807b156386fedc9e94b
    - [x] Settings: https://github.com/opnsense/docs/commit/8231b1321868a03fbacd8807b156386fedc9e94b
    - [x] Status: https://github.com/opnsense/docs/commit/8231b1321868a03fbacd8807b156386fedc9e94b
  - [ ] Network Time
    - [ ] General
    - [ ] GPS
    - [ ] PPS
    - [ ] Status
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [ ] Net-SNMP
  - [ ] OpenDNS
  - [ ] Unbound DNS
    - [ ] General
    - [ ] Overrides
    - [ ] Advanced
    - [ ] Access Lists
    - [ ] Statistics
    - [x] Log File https://docs.opnsense.org/manual/logging.html
  - [x] Web Proxy https://docs.opnsense.org/manual/proxy.html https://docs.opnsense.org/manual/how-tos/cachingproxy.html
    - [x] Administration https://docs.opnsense.org/manual/how-tos/proxywebfilter.html https://docs.opnsense.org/manual/how-tos/cachingproxy.html
    - [x] Log File https://docs.opnsense.org/manual/logging.html
- [x] Power not needed
  - [x] Reboot not needed
  - [x] Power Off not needed

Also see these issues:
- https://github.com/opnsense/docs/issues/99

**Comment by fabianfrz** [comment]
@MichaelDeciso you should also check the plugins, many of them do have more docs then core (for example all features of the nginx plugin, which are not for advanced users, should be there).

**Comment by fabianfrz** [comment]
@MichaelDeciso captive portal is here:
* https://docs.opnsense.org/manual/captiveportal.html?highlight=guest
* https://docs.opnsense.org/manual/how-tos/guestnet.html

**Comment by MichaelDeciso** [comment]
@fabianfrz 
> you should also check the plugins

I'll have to check with @AdSchellevis what the scope of this should be (I created this tracking issue on his request).

**Comment by fabianfrz** [comment]
@MichaelDeciso Backups: https://docs.opnsense.org/manual/how-tos/cloud_backup.html (does not conver restore etc.)

**Comment by fabianfrz** [comment]
@MichaelDeciso changelogs: #129
